/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet_final.interface_gr;

import static java.lang.Integer.parseInt;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import projet_final.Connexion;
import projet_final.Ecole;

/**
 *
 * @author sarto
 */
public class Gecoles extends javax.swing.JFrame {

    /**
     * Creates new form Gecoles
     */
    private Connexion c;
    public Gecoles(Connexion c) {
        this.c=c;
        initComponents();
        
    }
    public Gecoles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TNom = new javax.swing.JTextField();
        BExplorer = new javax.swing.JButton();
        BAdd = new javax.swing.JButton();
        Bsup = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BRetour = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Ecoles");

        TNom.setText("Ecole ampere");
        TNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNomActionPerformed(evt);
            }
        });

        BExplorer.setText("Explorer");
        BExplorer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExplorerActionPerformed(evt);
            }
        });

        BAdd.setText("Ajouter");
        BAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAddActionPerformed(evt);
            }
        });

        Bsup.setText("Supprimer");
        Bsup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsupActionPerformed(evt);
            }
        });

        jLabel2.setText("Nom");

        BRetour.setText("<- RETOUR");
        BRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRetourActionPerformed(evt);
            }
        });

        for(int i=0;i<Ecole.get_ecole_list().size();i++)
        {
            jComboBox1.addItem(Ecole.get_ecole_list().get(i).get_nom());
        }
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(BRetour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(BExplorer)
                .addGap(29, 29, 29)
                .addComponent(Bsup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(BAdd)
                .addGap(88, 88, 88))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(TNom, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BRetour))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BExplorer)
                    .addComponent(BAdd)
                    .addComponent(Bsup))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BExplorerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExplorerActionPerformed
        Ecole e = null;
        for(int i=0;i<Ecole.get_ecole_list().size();i++)
        {
            if(Ecole.get_ecole_list().get(i).get_nom().equals(jComboBox1.getSelectedItem().toString()))
                e=Ecole.get_ecole_list().get(i);
        }
        GClasses fenetre= new GClasses(e);
        fenetre.setVisible(true);
    }//GEN-LAST:event_BExplorerActionPerformed

    private void BAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAddActionPerformed
       String name =  TNom.getText();
       String requette_id = "SELECT MAX(id)+1, nom FROM ecole WHERE 1";
       ArrayList<String> result_id;
        try {
            result_id = this.c.remplirChampsRequete(requette_id);
            String[] res_id = result_id.get(0).split(",");
       String requette = "INSERT INTO ecole(id, nom) VALUES ("+parseInt(res_id[0])+", '"+name+"')";
       try {
            this.c.executeUpdate(requette);
        } catch (SQLException ex) {
            Logger.getLogger(Gecoles.class.getName()).log(Level.SEVERE, null, ex);
        }
      
            Ecole.add_ec_to_array(new Ecole(parseInt(res_id[0]), name));
            this.initComponents();
        } catch (SQLException ex) {
            Logger.getLogger(Gecoles.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        
        
     
        // TODO add your handling code here:
    }//GEN-LAST:event_BAddActionPerformed

    private void BsupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsupActionPerformed
        
        int idex = jComboBox1.getSelectedIndex();
        String value = jComboBox1.getSelectedItem().toString();
        String res_parse = "";
        for(int indice_char = 0; indice_char < value.length(); ++indice_char)
                                  {
                                      String b = "" + value.charAt(indice_char);
                                      if(!b.equals("\n"))
                                      {
                                      res_parse = res_parse + value.charAt(indice_char);
                                    }
                                      else
                                          break;
                                  }
        
        for(int i = 0; i<Ecole.get_ecole_list().size(); ++i)
            {  
                if(Ecole.get_ecole_list().get(i).get_nom().equals(res_parse));
                idex = Ecole.get_ecole_list().get(i).get_id();
            }
        res_parse = res_parse + "'";
        String requette = "DELETE FROM ecole WHERE id = "+idex;
        try {
            c.executeUpdate(requette);
        } catch (SQLException ex) {
            Logger.getLogger(Gecoles.class.getName()).log(Level.SEVERE, null, ex);
        }
    int i = 0;
        
        
    }//GEN-LAST:event_BsupActionPerformed

    private void TNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNomActionPerformed

    private void BRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRetourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BRetourActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gecoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gecoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gecoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gecoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gecoles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAdd;
    private javax.swing.JButton BExplorer;
    private javax.swing.JButton BRetour;
    private javax.swing.JButton Bsup;
    private javax.swing.JTextField TNom;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
